language: php

dist: xenial

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - COMPOSER_MEMORY_LIMIT=-1

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - composer global require --no-progress --no-scripts --no-plugins symfony/flex dev-master

install:
  - travis_retry composer update -n  --prefer-stable

script:
  - ./vendor/bin/phpunit -v

jobs:
  include:
    # Tests the lowest set of dependencies
    - php: 7.1
      env: LOWEST SYMFONY_DEPRECATIONS_HELPER=weak
      install:
        - travis_retry composer update -n --prefer-lowest --prefer-stable

    # Symfony 4.4
    - php: 7.3
      env: SYMFONY_REQUIRE="4.4.*"
      install:
        - travis_retry composer update -n

    # Symfony 5.0
    - php: 7.4
      env: SYMFONY_REQUIRE="5.0.*"
      install:
        - travis_retry composer update -n

    - stage: Code Quality
      env: CODING_STANDARDS
      php: 7.3
      script:
        - ./vendor/bin/phpcs

    - stage: Coverage
      php: 7.3
      install:
        - travis_retry composer update -n
      before_script:
        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
      script:
        - ./vendor/bin/phpunit -v --coverage-clover ./build/logs/clover.xml
#      after_script:
#        - php ./vendor/bin/coveralls -v
